--
-- Estrutura para tabela 'CIELO_VENDA_PAGTO'
--
CREATE TABLE 'CIELO_VENDA_PAGTO' (
  'ID_LINHA' int(11) NOT NULL,
  'TIPO_REGISTRO' int(1) NOT NULL,
  'NUMERO_PV' varchar(50) NOT NULL,
  'DTA_APRESENTACAO' date NOT NULL,
  'DTA_PREVISTA_PAGTO' date NOT NULL,
  'SINAL_VLR_LIQUIDO' varchar(1) NOT NULL,
  'VLR_LIQUIDO' decimal(10,2) DEFAULT NULL,
  'VLR_BRUTO' decimal(10,2) NOT NULL,
  'CODIGO_PRODUTO' int(3) NOT NULL,
  'DTA_EXECUCAO' datetime NOT NULL,
  'STATUS_PROCESSAMENTO' char(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Índices de tabela 'CIELO_VENDA_PAGTO'
--
ALTER TABLE 'CIELO_VENDA_PAGTO' ADD PRIMARY KEY ('ID_LINHA');

--
-- AUTO_INCREMENT de tabela 'CIELO_VENDA_PAGTO'
--
ALTER TABLE 'CIELO_VENDA_PAGTO' MODIFY 'ID_LINHA' int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;

